export const ALLOWED_DOMAINS_FOR_REGISTER = [
  "gmail.com",
  "mail.ru",
  "bk.ru",
  "internet.ru",
  "vk.com",
  "inbox.ru",
  "list.ru",
  "xmail.ru",
  "yandex.ru",
  "yandex.kz",
  "yandex.com",
  "ya.ru",
  "ya.com",
  "ya.kz",
  "outlook.com",
  "hotmail.com",
  "icloud.com",
  "proton.me",
  "pm.me",
  "ispark.kz",
];
export const ALLOWED_DOMAINS_FOR_RESTORE = [
  ...ALLOWED_DOMAINS_FOR_REGISTER,
  "shakarim.kz",
  "fortebank.com",
  "semaz.kz",
  "tehkomfort.kz",
  "naceks.kz",
  "smu.edu.kz",
  "karazhyra.kz",
  "rambler.com",
  "prokuror.gov.kz",
  "sm.nis.edu.kz",
  "nce.kz",
  "telecom.kz",
  "ilbers.kz",
  "iamrl.kz",
  "apgreman.kz",
  "maxamcorp.com",
  "nu.edu.kz",
  "homecredit.kz",
];

export const ROLES = {
  ADMIN: "admin",
  USER: "user",
  VOLUNTEER: "volunteer",
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];
