name: Build and Lint

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    lint-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies with Yarn Berry
              run: yarn install --immutable

            - name: Lint code
              run: yarn lint

            - name: Build project
              run: yarn build
